# name: Build and Test

# on: [push, pull_request]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install dependencies
#         working-directory: ./client
#         run: npm install
#       - name: Build app
#         working-directory: ./client
#         run: npm run build
#       - name: Test app
#         working-directory: ./client
#         run: npm test

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      run: |
        cd client
        npm install -g n
        n ${{ matrix.node-version }}
      shell: bash
    - name: Run CI
      run: npm ci
    - name: Build app
      run: npm run build --if-present
    - name: Test app
      run: npm test
