name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Build app
        working-directory: ./client
        run: npm run build
      - name: Test app
        working-directory: ./client
        run: npm test
